
version: 2
jobs:

  install-deps:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: install_deps
          command: |
            apt -y update
            apt -y install cmake
      - run:
          name: install_rust_toolchains
          command: |
            rustup update
            rustup install beta
            rustup install nightly || rustup install nightly-$(date --date="@$(expr $(date +%s) - 86000)" '+%F') || true

  rust-test-stable:
    docker:
      - image: rust:latest
    steps:
      - run: cargo test

  rust-test-beta:
    docker:
      - image: rust:latest
    steps:
      - run: cargo +beta test

  rust-test-nightly:
    docker:
      - image: rust:latest
    steps:
      - run: cargo +nightly test

workflows:
  version: 2
  run-tests:
    jobs:
      - install-deps
      - rust-test-stable:
          requires:
            - install-deps
      - rust-test-beta:
          requires:
            - install-deps
      - rust-test-nightly:
          requires:
            - install-deps

